version: '3'

services:
  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin_data
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - db
 
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: "exit 0"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: workout_db

volumes:
  postgres_data:
  backend: