version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      # test: "exit 0"
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: workout_db

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis_service:
        condition: service_started
    # command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    command: ["bash", "-c", "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"]

    ports:
      - 8000:8000
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin_data
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - db
 
  redis_service:
    image: "redis"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  backend: