"""init

Revision ID: 7445b3784735
Revises: 
Create Date: 2024-03-09 17:50:26.880760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7445b3784735'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('muscle_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='muscle_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_muscle_id', 'muscle', ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)

    op.create_table('excercise',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('excercise_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='excercise_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='excercise_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_excercise_id', 'excercise', ['id'], unique=False)

    op.create_table('workout_plan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='workout_plan_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workout_plan_pkey')
    )
    op.create_index('ix_workout_plan_id', 'workout_plan', ['id'], unique=False)

    op.create_table('excercise_workout',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('excercise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repetitions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excercise_id'], ['excercise.id'], name='excercise_workout_excercise_id_fkey'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout_plan.id'], name='excercise_workout_workout_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='excercise_workout_pkey')
    )
    op.create_index('ix_excercise_workout_id', 'excercise_workout', ['id'], unique=False)
    
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('excercise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('achieved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repetitions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excercise_id'], ['excercise.id'], name='goal_excercise_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='goal_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='goal_pkey')
    )
    op.create_index('ix_goal_id', 'goal', ['id'], unique=False)

    op.create_table('excercise_muscle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('excercise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('muscle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excercise_id'], ['excercise.id'], name='excercise_muscle_excercise_id_fkey'),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscle.id'], name='excercise_muscle_muscle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='excercise_muscle_pkey')
    )
    op.create_index('ix_excercise_muscle_id', 'excercise_muscle', ['id'], unique=False)

    op.create_table('weight_tracker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='weight_tracker_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='weight_tracker_pkey')
    )
    op.create_index('ix_weight_tracker_id', 'weight_tracker', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weight_tracker_id', table_name='weight_tracker')
    op.drop_table('weight_tracker')
    op.drop_index('ix_workout_plan_id', table_name='workout_plan')
    op.drop_table('workout_plan')
    op.drop_index('ix_excercise_muscle_id', table_name='excercise_muscle')
    op.drop_table('excercise_muscle')
    op.drop_index('ix_goal_id', table_name='goal')
    op.drop_table('goal')
    op.drop_index('ix_excercise_id', table_name='excercise')
    op.drop_table('excercise')
    op.drop_index('ix_excercise_workout_id', table_name='excercise_workout')
    op.drop_table('excercise_workout')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_muscle_id', table_name='muscle')
    op.drop_table('muscle')
    # ### end Alembic commands ###
